openid-connect:
  azure:
    client-id-key:
    client-secret-key:
    azure_function_key: '1234'
    SharedAccessKey: 'test=uty'
    azure_sql_password: 'test123R'
    MY_TEST_SECRET: 'test'
    adobe_service_token: '123test'
    azure_sql_password: '234ikt'
